// IMPORTING NECESSARY FILES
    // IMPORTING NECESSARY HOOKS
    // IMPORTING NECESSARY COMPONENTS
    // IMPORTING NECESSARY CONFIGS
   // IMPORTING NECESSARY MODULES

// EXPORTING DEFAULT APPLYFORLAUNCHPADPAGE
export default function ApplyForLaunchpadPage(){
    // A STATE TO KEEP TRACK OF RIGHT STATE OF SIGN IN BUTTON
    
    // A STATE TO KEEP TRACK OF FORM DATA

    // OBTAINING USERCONTEXT FROM HOOK

    // A FUNCTION TO SIGN OUT USER VIA GITHUB

    // A FUNCTION TO SIGN OUT USERS VIA EMAIL

    return(
        // A CONTAINER FOR THE WHOLE PAGE
        <div className="min-h-[100vh] scroll-smooth box-border transition-all duration-500 ease-in-out flex justify-center items-center">
            {/* A SIGNINMODAL COMPONANT THAT HANDLES AUTHENTICATION */}
        </div>
    )
}